name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Install Node.js
      uses: actions/setup-node@v2.1.4
    - name: Install Packages
      run: npm install
      env:
        CI: true
    - name: Lint
      run: npm run lint -- --quiet

