name: CI
on: [ push, pull_request ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: actions/setup-node@v2.5.2
    - run: npm install
      env:
        CI: true
    - run: npm run lint --if-present -- --quiet
    - run: npm run build
    - run: npm run test --if-present -- --quiet
    - run: npm run coverage --if-present -- --quiet

